### ISSUE TITLE
PA: Review: User Authentication

### ISSUE THREAD

**Issue by azuzunaga** [azuzunaga/lucha#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by azuzunaga** [comment]
Added error handling and styling on login and sign up forms. Should be all set.

**Comment by AAlfarho** [comment]
Great job on the User Auth, kudos!

The clicking effect on the demo user looks amazing.
The issues we discussed are properly implemented and pushed live.
